const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const csInterface = new CSInterface();

let watchFolder = null;
let watcher = null;
let isWatching = false;
let processingFiles = new Set(); // Track files currently being imported
let sessionHashes = new Set();  // Track unique file signatures in this session

const btnSelect = document.getElementById('btn-select');
const btnToggle = document.getElementById('btn-toggle');
const btnTest = document.getElementById('btn-test');
const btnReload = document.getElementById('btn-reload');
const chkAutoCopy = document.getElementById('chk-auto-copy');
const statusText = document.getElementById('id-status-text');
const logContainer = document.getElementById('log-container');

/**
 * Event Listener for items added to project (dispatched from host/index.jsx)
 */
csInterface.addEventListener("com.binsync.itemAdded", (event) => {
    if (!chkAutoCopy.checked || !watchFolder) return;
    
    try {
        const data = JSON.parse(event.data);
        const mediaPath = data.mediaPath;
        const binPath = data.binPath; // e.g. "Footage/B-Roll"
        const name = data.name;

        // Correctly check if the file is already inside the watch folder
        const relativeToWatch = path.relative(watchFolder, mediaPath);
        const isInsideWatch = relativeToWatch && !relativeToWatch.startsWith('..') && !path.isAbsolute(relativeToWatch);

        if (isInsideWatch) {
            return;
        }

        log(`External Import Detected: ${name}`);

        
        // Construct target path
        const targetDir = path.join(watchFolder, binPath);
        const targetPath = path.join(targetDir, name);

        // Ensure directory exists
        if (!fs.existsSync(targetDir)) {
            fs.mkdirSync(targetDir, { recursive: true });
        }

        // Check if destination already exists (maybe same name, different content?)
        if (fs.existsSync(targetPath)) {
            const sourceHash = getShallowHash(mediaPath);
            const targetHash = getShallowHash(targetPath);
            if (sourceHash === targetHash) {
                log(`Skipped Copy: ${name} (File already in watch folder)`);
                return;
            } else {
                // Same name but different - append suffix or ignore?
                // For safety, let's not overwrite. Add timestamp.
                const ext = path.extname(name);
                const base = path.basename(name, ext);
                const newName = `${base}_${Date.now()}${ext}`;
                const newTargetPath = path.join(targetDir, newName);
                
                log(`Copying with unique name: ${newName}...`);
                fs.copyFileSync(mediaPath, newTargetPath);
                
                // Add to session hashes so the watcher skips it
                const hash = getShallowHash(mediaPath);
                if (hash) sessionHashes.add(hash);
                log(`Copied: ${newName} to watch folder.`, "success");
                return;
            }
        }

        log(`Copying to watch folder: ${name}...`);
        fs.copyFileSync(mediaPath, targetPath);
        
        // Add to session hashes so the watcher skips it
        const hash = getShallowHash(mediaPath);
        if (hash) sessionHashes.add(hash);
        
        log(`Copied: ${name} to watch folder.`, "success");

    } catch (e) {
        log("Auto-copy Error: " + e.message, "error");
    }
});

/**
 * Generates a "shallow" hash of a file for fast duplicate detection.
 * Samples the start, middle, and end of the file + file size.
 */
function getShallowHash(filePath) {
    try {
        const stats = fs.statSync(filePath);
        if (stats.isDirectory()) return null;

        const size = stats.size;
        const SAMPLE_SIZE = 65536; // 64KB
        const buffer = Buffer.alloc(SAMPLE_SIZE * 3 + 8); // 3 samples + 8 bytes for size
        
        const fd = fs.openSync(filePath, 'r');
        
        // Sample 1: Start
        fs.readSync(fd, buffer, 0, SAMPLE_SIZE, 0);
        
        // Sample 2: Middle
        const middlePos = Math.floor(size / 2);
        fs.readSync(fd, buffer, SAMPLE_SIZE, SAMPLE_SIZE, middlePos);
        
        // Sample 3: End
        const endPos = Math.max(0, size - SAMPLE_SIZE);
        fs.readSync(fd, buffer, SAMPLE_SIZE * 2, SAMPLE_SIZE, endPos);
        
        // Add size to the end of buffer
        buffer.writeBigInt64BE(BigInt(size), SAMPLE_SIZE * 3);
        
        fs.closeSync(fd);
        
        return crypto.createHash('md5').update(buffer).digest('hex');
    } catch (e) {
        console.error("Hash error:", e);
        return null;
    }
}

// Folders generated by Premiere Pro or system that should be ignored
const EXCLUDED_FOLDERS = [
    'Adobe Premiere Pro Auto-Save',
    'Adobe Premiere Pro Captured Audio',
    'Adobe Premiere Pro Captured Video',
    'Adobe Premiere Pro Video Previews',
    'Adobe Premiere Pro Audio Previews',
    'Encoded Files',
    'Media Cache Files',
    'Peak Files'
];

function log(msg, type = '') {
    const div = document.createElement('div');
    if (type) div.className = type;
    div.textContent = `[${new Date().toLocaleTimeString()}] ${msg}`;
    logContainer.appendChild(div);
    logContainer.scrollTop = logContainer.scrollHeight;
}

/**
 * Checks if a path contains any excluded Adobe folders.
 */
function isExcluded(filePath) {
    const parts = filePath.split(path.sep);
    return parts.some(part => EXCLUDED_FOLDERS.includes(part));
}

/**
 * Ensures the ExtendScript host is loaded.
 */
function ensureHostLoaded(callback) {
    csInterface.evalScript('typeof($._ext_PPRO)', (result) => {
        if (result === 'undefined') {
            log("Host script not loaded. Attempting to load host/index.jsx...");
            const extensionPath = csInterface.getSystemPath(SystemPath.EXTENSION);
            const scriptPath = path.join(extensionPath, 'host', 'index.jsx').replace(/\\/g, '/');
            const loadScript = `$.evalFile("${scriptPath}")`;
            csInterface.evalScript(loadScript, (loadResult) => {
                if (loadResult === "EvalScript error.") {
                    log("Critical Error: Failed to load host/index.jsx via evalFile.", "error");
                    callback(false);
                } else {
                    log("Host script loaded manually.", "success");
                    callback(true);
                }
            });
        } else {
            callback(true);
        }
    });
}

// RELOAD PANEL
btnReload.addEventListener('click', () => {
    location.reload();
});

// TEST CONNECTION
btnTest.addEventListener('click', () => {
    log("Testing connection to Premiere...");
    ensureHostLoaded((success) => {
        if (!success) return;
        csInterface.evalScript('$._ext_PPRO.getOrCreateBin("")', (result) => {
            if (result === "EvalScript error.") {
                log("Error: ExtendScript link failed.", "error");
            } else if (result === "null") {
                 log("Error: No active project found in Premiere Pro.", "error");
            } else {
                log("Success: Connection verified.", "success");
            }
        });
    });
});

btnSelect.addEventListener('click', () => {
    try {
        const result = window.cep.fs.showOpenDialog(false, true, "Select Folder to Watch", "", []);
        if (result.data && result.data.length > 0) {
            let selectedPath = result.data[0];
            if (selectedPath.indexOf('file://') === 0) {
                selectedPath = decodeURI(selectedPath.replace('file://', ''));
                if (process.platform === 'win32' && selectedPath.indexOf('/') === 0) {
                    selectedPath = selectedPath.substring(1);
                }
            }
            watchFolder = selectedPath;
            statusText.textContent = `Watching: ${watchFolder}`;
            btnToggle.disabled = false;
            log(`Target set: ${watchFolder}`);
        }
    } catch (e) {
        log("Dialog Error: " + e.message, "error");
    }
});

btnToggle.addEventListener('click', () => {
    if (isWatching) {
        stopWatching();
    } else {
        startWatching();
    }
});

/**
 * Recursively scans a directory and imports all files.
 * Process files in current directory FIRST, then recurse into subdirectories.
 * This ensures high-res media exists before its proxies are attached.
 */
async function scanAndImport(dir, rootDir) {
    const items = fs.readdirSync(dir);
    
    // Ensure the current folder exists as a bin in Premiere
    if (dir !== rootDir) {
        const relativePath = path.relative(rootDir, dir);
        const folderName = path.basename(dir).toLowerCase();
        
        // Skip creating bins for special proxy folders
        if (folderName === 'proxy' || folderName === 'proxies') {
            // Do not create bin, but still scan children for attachment
        } else {
            await handleFolderAdded(relativePath);
        }
    }

    const subdirs = [];
    const files = [];

    for (const item of items) {
        const fullPath = path.join(dir, item);
        const stat = fs.statSync(fullPath);
        if (stat.isDirectory()) {
            if (!EXCLUDED_FOLDERS.includes(item)) {
                subdirs.push(fullPath);
            }
        } else {
            // Ignore system files
            if (!item.startsWith('.') && !item.endsWith('.prlock') && !item.endsWith('.prproj')) {
                files.push({ fullPath, item });
            }
        }
    }

    // 1. Process all local files first
    for (const fileObj of files) {
        const relativePath = path.relative(rootDir, fileObj.fullPath);
        await handleFileAdded(fileObj.fullPath, relativePath);
    }

    // 2. Then recurse into subdirectories
    for (const subdir of subdirs) {
        await scanAndImport(subdir, rootDir);
    }
}

function startWatching() {
    if (!watchFolder) return;
    
    ensureHostLoaded(async (success) => {
        if (!success) return;
        
        try {
            isWatching = true;
            btnToggle.textContent = "Stop Watching";
            btnToggle.classList.add('active');
            
            log(`Starting initial scan of: ${watchFolder}...`);
            await scanAndImport(watchFolder, watchFolder);
            log(`Initial scan complete. Watcher active.`, "success");

            watcher = fs.watch(watchFolder, { recursive: true }, (eventType, filename) => {
                if (filename && eventType === 'rename') {
                    const fullPath = path.join(watchFolder, filename);
                    
                    if (isExcluded(filename)) return;
                    if (filename.endsWith('.prlock') || filename.endsWith('.prproj')) return;

                    // If we are already processing this exact path, ignore the duplicate event
                    if (processingFiles.has(fullPath)) return;

                    setTimeout(() => {
                        if (fs.existsSync(fullPath)) {
                            const isHidden = filename.split(path.sep).some(part => part.startsWith('.'));
                            if (isHidden) return;

                            if (fs.lstatSync(fullPath).isDirectory()) {
                                handleFolderAdded(filename);
                            } else {
                                handleFileAdded(fullPath, filename);
                            }
                        }
                    }, 200);
                }
            });
        } catch (e) {
            log("Watcher Error: " + e.message, "error");
            stopWatching();
        }
    });
}

function stopWatching() {
    if (watcher) {
        watcher.close();
        watcher = null;
    }
    isWatching = false;
    btnToggle.textContent = "Start Watching";
    btnToggle.classList.remove('active');
    log(`Watcher stopped.`);
    processingFiles.clear();
}

/**
 * Calls ExtendScript to create or verify a bin hierarchy.
 */
function handleFolderAdded(relativePath) {
    const parts = relativePath.split(path.sep);
    if (parts.some(p => {
        const lp = p.toLowerCase();
        return lp === 'proxy' || lp === 'proxies';
    })) {
        return Promise.resolve();
    }

    return new Promise((resolve) => {
        const normalizedRelative = relativePath.replace(/\\/g, '/').replace(/^\.\//, '');
        const script = `$._ext_PPRO.getOrCreateBin("${normalizedRelative}")`;
        csInterface.evalScript(script, (result) => {
            if (result === "success") {
                log(`Verified Bin: ${normalizedRelative}`, "success");
            }
            resolve();
        });
    });
}

/**
 * Normalizes paths and calls ExtendScript to import the file or attach as proxy.
 */
function handleFileAdded(fullPath, relativePath) {
    if (processingFiles.has(fullPath)) return Promise.resolve();
    processingFiles.add(fullPath);

    return new Promise((resolve) => {
        const normalizedFull = fullPath.replace(/\\/g, '/');
        const filename = path.basename(fullPath);
        const proxyDir = path.dirname(fullPath);
        const folderName = path.basename(proxyDir).toLowerCase();

        // CHECK IF IT SHOULD BE A PROXY
        if (folderName === 'proxy' || folderName === 'proxies') {
            const parentDir = path.dirname(proxyDir);
            const highResPath = path.join(parentDir, filename).replace(/\\/g, '/');

            log(`Attaching Proxy: ${filename}...`);
            const script = `$._ext_PPRO.attachProxyByPath("${normalizedFull}", "${highResPath}")`;
            csInterface.evalScript(script, (result) => {
                processingFiles.delete(fullPath);
                if (result === "true") {
                    log(`Attached Proxy: ${filename}`, "success");
                } else {
                    log(`Proxy skipped: No matching media found for ${filename}`);
                }
                resolve();
            });
            return;
        }

        // NORMAL IMPORT LOGIC
        const fileHash = getShallowHash(fullPath);
        if (fileHash && sessionHashes.has(fileHash)) {
            log(`Skipped: ${relativePath} (Duplicate content detected via hash)`);
            processingFiles.delete(fullPath);
            return resolve();
        }

        const normalizedRelative = relativePath.replace(/\\/g, '/').replace(/^\.\//, '');
        const pathParts = normalizedRelative.split('/');
        pathParts.pop(); 
        const binHierarchy = pathParts.join('/');

        const script = `$._ext_PPRO.importFileToBin("${normalizedFull}", "${binHierarchy}")`;
        
        csInterface.evalScript(script, (result) => {
            processingFiles.delete(fullPath);

            if (result === "EvalScript error.") {
                log(`Critical Error: script execution failed for ${normalizedRelative}`, "error");
            } else if (result === "exists") {
                log(`Skipped: ${normalizedRelative} (Path already in project)`);
                if (fileHash) sessionHashes.add(fileHash);
            } else if (result.indexOf("Error:") === 0) {
                log(`${result} (${normalizedRelative})`, "error");
            } else if (result === "false") {
                log(`Import failed for: ${normalizedRelative}`, "error");
            } else if (result === "true") {
                log(`Imported: ${normalizedRelative}`, "success");
                if (fileHash) sessionHashes.add(fileHash);
            }
            resolve();
        });
    });
}
